name: Tests

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  tests:
    name: Tests
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: [ '18.x', '20.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Run Build
        run: npm run build

      - name: Run Tests
        run: npm test

  doc-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm ci
      - name: Build with VitePress
        run: npm run docs:build
